# Generated by Django 3.0.2 on 2020-01-04 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='guest', max_length=5)),
                ('title', models.TextField(default='TestVideo')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
